### PR TITLE
[RTC] Update for setdatetime and settime

### PR DESCRIPTION
**Pull request by Lorenzooone**

### CODE REVIEW

**Comment by Lorenzooone** [comment]
Do note: the second commit can be axed, if it's not good enough.
The RTC status is queried only when setting the time, as, when reading the time, it's implicit in the way the AM/PM flag works (in theory).

**Comment by Lorenzooone** [comment]
I have honestly no idea whether 1d3460c3df7069691d698dbe3087f0b34d880481 should be kept or not. Regular carts work without it, but the EZ Flash Omegas don't. Up to you, honestly.
Just sharing this knowledge is already good.

**Comment by felixjones** [comment]
> I have honestly no idea whether [1d3460c](https://github.com/felixjones/agbabi/commit/1d3460c3df7069691d698dbe3087f0b34d880481) should be kept or not. Regular carts work without it, but the EZ Flash Omegas don't. Up to you, honestly. Just sharing this knowledge is already good.

I have some EZO detection code lying around somewhere, might be worth wrapping this in a check for that

Do we know exactly how many cycles need to be waited before the writes are good? I would prefer a loop written in assembly to make it obvious that N cycles of delay is required

**Comment by Lorenzooone** [comment]
I haven't measured the cycles precisely. However, if we want really precise waiting, it should be moved to IWRAM as well...?

**Comment by felixjones** [comment]
> I haven't measured the cycles precisely. However, if we want really precise waiting, it should be moved to IWRAM as well...?

Eh, definitely don't want this in IWRAM. I was thinking make the delay as short as possible, but really it's just RTC time set code, I'm sure a short delay doesn't matter

**Comment by Lorenzooone** [comment]
> > I haven't measured the cycles precisely. However, if we want really precise waiting, it should be moved to IWRAM as well...?
> 
> Eh, definitely don't want this in IWRAM. I was thinking make the delay as short as possible, but really it's just RTC time set code, I'm sure a short delay doesn't matter

I was more thinking about having a small "delay function" in IWRAM, that, regardless of what the EWRAM/ROM settings are, always executes the same number of requested cycles. It could be useful for other stuff as well. But I understand it's kind of weird...?

**Comment by Lorenzooone** [comment]
Another way would be to implement a backoff mechanism. Though that would mean adding a read of the rtc to the function that sets it.
It would be faster for regular carts, though.

**Comment by felixjones** [comment]
Going to merge this into rtc2, and I'll do a cleaning pass over it

Great work!

**Pull request merged**
